test: &default

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: linr
  password: fdasf
  signature: sfds-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: linr@aa.com

  # #Product Name
  product_name: test

  # # bundle version
  version: 4.8.1

  # # Singleton server
  vip_server:

  # # translation bundle Path
  translation_bundle: ./spec/config/locales/l10n/bundles

  # # source bundle Path
  source_bundle: ./spec/config/locales/default

  # # memory cache's expration(minutes), default value is 24*60
  cache_expiry_period: 10

  # # the default language used to load local source bundle
  default_language: en

  log_file: ./unit_test.log

  log_level: DEBUG

development:
  <<: *default

production:
  <<: *default
  log_level: INFO
