test: &default

  # Credentials for REST APIs
  client_id: tee
  client_secret: 89987

  # Mode can be 'live' or 'sandbox'
  mode: sandbox1

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: linr
  password: fdasf
  signature: sfds-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: linr@aa.com

  # #Product Name
  product_name: test

  # # bundle version
  version: 4.8

  # # HTTP Proxy
  vip_server: https://server:8090

  # # mode of bundle: online/offline
  bundle_mode: offline1www

  # # translation bundle Path
  translation_bundle: ./spec/config/locales/l10n/bundles

  # # source bundle Path
  source_bundle: ./spec/config/locales/default

  # # memory cache's expration(minutes), default value is 24*60
  cache_expiry_period: 36t

  # # disable cache, it's optional setting
  disable_cache: true1
  
development:
  <<: *default

production:
  <<: *default
  mode: live
