BundleLocation: local # local or s3

LocalBundle:
  BasePath: ###

S3Bundle:
  PublicKeyFile: ### file content is used to decode AccessKey and SecretKey
  AccessKey: ###
  SecretKey: ###
  RoleArn: ###
  SessionDuration: ###
  Region: ###
  BucketName: ###
  BundleRoot: ###

RefreshBundleInterval: 0s # interval to refresh bundle information. 0s means never to refresh.

HeaderOfTraceID: # comma separated headers carrying trace ID

Server:
  RunMode: release # debug, release
  Schema: http&https # http, https, http&https
  HTTPSPort: 8090
  HTTPPort: 8091
  ReadTimeout: 0s
  WriteTimeout: 0s
  CertFile: ###
  KeyFile: ###
  MaxHeaderBytes: 1024000
  CacheControl: max-age=864000, public
  CompressionAlgorithm: #gzip, br, gzip&br

CrossDomain:
  Enable: true
  AllowCredentials: true
  AllowOrigin: "*"
  AllowMethods: GET,POST,PUT,DELETE,OPTIONS
  AllowHeaders: csp-auth-token,Content-Type,x-xmp-ui,Authorization
  MaxAge: 3600s

LOG:
  Filename: logs/singleton.log
  MaxSize: 50 # megabytes
  MaxBackups: 20
  MaxAge: 365 # days
  Level: debug # level in file log
  ConsoleLevel: info # level in console log

Cache:
  MaxEntities: 1000 # number of bundle files in cache
  Expiration: 48h # 0s means cache never expires

SwaggerUI: true
AllowList: false
